//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spreadsheet.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public Nullable<double> ID { get; set; }
        public string artwork_name { get; set; }
        public string image_name_prefix { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<double> vendor { get; set; }
        public string price_parent { get; set; }
        public string weight { get; set; }
        public string is_pixfizz_customizable { get; set; }
        public string tags { get; set; }
        public bool soft_launch { get; set; }
    }
}
