#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spreadsheet.Web.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="shoppaul")]
	public partial class SPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    #endregion
		
		public SPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["shoppaulConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _artwork_name;
		
		private string _image_name_prefix;
		
		private string _title;
		
		private string _description;
		
		private string _type;
		
		private System.Nullable<double> _vendor;
		
		private string _price_parent;
		
		private string _weight;
		
		private string _is_pixfizz_customizable;
		
		private string _tags;
		
		private bool _soft_launch;
		
		private bool _is_dirty;
		
		private System.Guid _SID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onartwork_nameChanging(string value);
    partial void Onartwork_nameChanged();
    partial void Onimage_name_prefixChanging(string value);
    partial void Onimage_name_prefixChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnvendorChanging(System.Nullable<double> value);
    partial void OnvendorChanged();
    partial void Onprice_parentChanging(string value);
    partial void Onprice_parentChanged();
    partial void OnweightChanging(string value);
    partial void OnweightChanged();
    partial void Onis_pixfizz_customizableChanging(string value);
    partial void Onis_pixfizz_customizableChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void Onsoft_launchChanging(bool value);
    partial void Onsoft_launchChanged();
    partial void Onis_dirtyChanging(bool value);
    partial void Onis_dirtyChanged();
    partial void OnSIDChanging(System.Guid value);
    partial void OnSIDChanged();
    #endregion
		
		public product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artwork_name", DbType="NVarChar(255)")]
		public string artwork_name
		{
			get
			{
				return this._artwork_name;
			}
			set
			{
				if ((this._artwork_name != value))
				{
					this.Onartwork_nameChanging(value);
					this.SendPropertyChanging();
					this._artwork_name = value;
					this.SendPropertyChanged("artwork_name");
					this.Onartwork_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_name_prefix", DbType="NVarChar(255)")]
		public string image_name_prefix
		{
			get
			{
				return this._image_name_prefix;
			}
			set
			{
				if ((this._image_name_prefix != value))
				{
					this.Onimage_name_prefixChanging(value);
					this.SendPropertyChanging();
					this._image_name_prefix = value;
					this.SendPropertyChanged("image_name_prefix");
					this.Onimage_name_prefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor", DbType="Float")]
		public System.Nullable<double> vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				if ((this._vendor != value))
				{
					this.OnvendorChanging(value);
					this.SendPropertyChanging();
					this._vendor = value;
					this.SendPropertyChanged("vendor");
					this.OnvendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_parent", DbType="NVarChar(255)")]
		public string price_parent
		{
			get
			{
				return this._price_parent;
			}
			set
			{
				if ((this._price_parent != value))
				{
					this.Onprice_parentChanging(value);
					this.SendPropertyChanging();
					this._price_parent = value;
					this.SendPropertyChanged("price_parent");
					this.Onprice_parentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="NVarChar(50)")]
		public string weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_pixfizz_customizable", DbType="NVarChar(50)")]
		public string is_pixfizz_customizable
		{
			get
			{
				return this._is_pixfizz_customizable;
			}
			set
			{
				if ((this._is_pixfizz_customizable != value))
				{
					this.Onis_pixfizz_customizableChanging(value);
					this.SendPropertyChanging();
					this._is_pixfizz_customizable = value;
					this.SendPropertyChanged("is_pixfizz_customizable");
					this.Onis_pixfizz_customizableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(255)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soft_launch", DbType="Bit NOT NULL")]
		public bool soft_launch
		{
			get
			{
				return this._soft_launch;
			}
			set
			{
				if ((this._soft_launch != value))
				{
					this.Onsoft_launchChanging(value);
					this.SendPropertyChanging();
					this._soft_launch = value;
					this.SendPropertyChanged("soft_launch");
					this.Onsoft_launchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_dirty", DbType="Bit NOT NULL")]
		public bool is_dirty
		{
			get
			{
				return this._is_dirty;
			}
			set
			{
				if ((this._is_dirty != value))
				{
					this.Onis_dirtyChanging(value);
					this.SendPropertyChanging();
					this._is_dirty = value;
					this.SendPropertyChanged("is_dirty");
					this.Onis_dirtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
